import type { Metadata } from "next";
import { Manrope } from 'next/font/google'
import { Poppins } from 'next/font/google'
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // customize as needed
  variable: '--font-manrope', // for Tailwind CSS
  display: 'swap',
})
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Choose the weights you need
  variable: '--font-poppins', // Required for Tailwind integration
  display: 'swap',
})


export const metadata: Metadata = {
  title: "Splurjj",
  description: "Generated by splurjj description",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${manrope.variable} antialiased`}>
        <Navbar />
        {children}
        <Footer />
        <Toaster />
        <ToastContainer />
      </body>
    </html>
  );
}
